version: "3.8"
services:

  # nginx service
  web:
    container_name: "web"
    image: nginx:alpine
    # depends_on:
      # - app
    ports:
      - "8080:8080"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./frontend:/frontend

  # application service
  
  app:
    container_name: "app"
    build: .
    command: bash -c 'uvicorn main:app --host 0.0.0.0'
    ports:
      - "8000:8000"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # command: redis-server --slaveof redis-master 6379 
    # networks:
    #   - custom